import Head from 'next/head';
import Image from 'next/image';
import { Container } from 'react-bootstrap';

import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';
import Header from '../components/Header';
import HomeScreen from '../screens/HomeScreen';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'
          integrity='sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=='
          crossorigin='anonymous'
          referrerpolicy='no-referrer'
        />
      </Head>

      <Header />
      <main className='py-3'>
        <Container className='main'>
          <HomeScreen />
        </Container>
      </main>
      <Footer />
    </div>
  );
}
